tupla1 = ("osvaldo", "rg", "cpf")
tupla2 = ("ricardo", "rg", "cpf")
tupla3 = ("jonas", "rg", "cpf")
tupla4 = ("raissa",  "rg", "cpf")
tupla5 = ("vanessa", "rg", "cpf")
tupla6 = ("davi", "rg", "cpf")
tupla7 = ("enzo", "rg", "cpf")
tupla8 = ("duda",  "rg", "cpf")
lista = [tupla1,tupla2,tupla3,tupla4,tupla5,tupla6,tupla7,tupla8]
tupla9 = ('violino','piano')
tupla10 = ('escola','caderno')
tupla11 = ('lapis','caneta')
lista.append(tupla9)
lista.append(tupla10)
lista.append(tupla11)
del(lista[7])
print(lista)